### ISSUE TITLE
Оновлена пропозиція щодо help

### ISSUE THREAD

**Issue by OleksaSolo** [lexxai/goit_python_core_project_team_11#10]
стр.231 file class_commands.py:

return "\nThe full command syntax is available on request: command ? [Example: +a ?] \nList of commands: \n" + ", ".join(sorted(commands))

на мій погляд додасть ясності як уточнити синтаксис команди.

**Comment by lexxai** [comment]
Можете протестувати у окремій гілці ?

**Comment by OleksaSolo** [comment]
Вже протестував. Працює.
![4df37-clip-61kb](https://github.com/lexxai/goit_python_core_project_team_11/assets/131910119/153bb965-47c4-4a84-8608-ab62f472987e)

**Comment by lexxai** [comment]
Додавайте до dev

**Comment by OleksaSolo** [comment]
Зроблено.
update help #13

**Comment by lexxai** [comment]
![зображення](https://github.com/lexxai/goit_python_core_project_team_11/assets/3278842/f8532920-d72a-4946-9b12-cb1c0ab02e55)

**Comment by OleksaSolo** [comment]
Виправлю. Пару хв.

**Comment by OleksaSolo** [comment]
![555fb-clip-61kb](https://github.com/lexxai/goit_python_core_project_team_11/assets/131910119/6b4b81b5-62c1-4b5d-b088-15f980eac750)
